# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Product.create(title: 'Windows 8 Professional')
Product.create(title: 'Apple iPad, 3rd Generation')
Product.create(title: 'Maingear Alpha')
Product.create(title: 'Vizio CT14-A2')
Product.create(title: 'Amazon Kindle Paperwhite')
Product.create(title: 'Samsung Galaxy S III')
Product.create(title: 'Intel Ivy Bridge CPUs')
Product.create(title: 'Panasonic Smart Viera VT50 HDTVs')
Product.create(title: 'Asus RT-AC66U')
Product.create(title: 'Lenovo IdeaPad Y580 ')
Product.create(title: 'Microsoft Surface RT')
Product.create(title: 'Audioengine 5+')
Product.create(title: 'Amazon Kindle Fire HD')
Product.create(title: 'Google Nexus 7')
Product.create(title: 'Falcon Northwest Tiki')
Product.create(title: 'Adobe Creative Suite 6 ')
Product.create(title: 'Sony Tap 20')
Product.create(title: 'Raspberry Pi')
Product.create(title: 'Dell UltraSharp U2713HM')
Product.create(title: 'Jawbone Big Jambox')
Product.create(title: 'Olympus OM-D E-M5')
Product.create(title: 'Apple iPhone 5')
Product.create(title: 'Stardock Start8')
Product.create(title: 'Apple MacBook Pro with Retina Display')
Product.create(title: 'B&amp;N Nook Simple Touch with GlowLight')
Product.create(title: 'Razer BlackWidow Ultimate Gaming Keyboard')
Product.create(title: 'Western Digital MyBook Thunderbolt Duo')
Product.create(title: 'Linksys WUMC710 Media Connector')
Product.create(title: 'Lenovo IdeaCentre A720')
Product.create(title: 'Sonos Sub')
Product.create(title: 'MicroExpress MicroFlex 37B')
Product.create(title: 'Mass Effect 3')
Product.create(title: 'D-Link DCS-5222L')
Product.create(title: 'HP ZR2440w')
Product.create(title: 'Sony Bloggie Live MHS-TS55')
Product.create(title: 'Nvidia GeForce GTX 680')
Product.create(title: 'Angry Birds Space')
Product.create(title: 'Arcam rPAC')
Product.create(title: 'AMD Radeon HD 7970 GHz Edition')
Product.create(title: 'Adobe Lightroom 4.2')
Product.create(title: 'Asus RT-N66U')
Product.create(title: 'Velodyne vPulse')
Product.create(title: 'Vizio CA27-A1')
Product.create(title: 'Apple iPod touch—5th generation ')
Product.create(title: 'Astro A50 Wireless Headset')
Product.create(title: 'Apple iPad Mini')
Product.create(title: 'Google Hangouts')
Product.create(title: 'Alienware M17x-R4')
Product.create(title: 'Logitech Ultrathin Keyboard Cover')
Product.create(title: 'The Walking Dead')
Product.create(title: 'Vivint Home Automation')
Product.create(title: 'Sensible Vision Fast Access')
Product.create(title: 'Libratone Zipp')
Product.create(title: 'Vizio M3D470KD')
Product.create(title: 'AT&amp;T U-verse')
Product.create(title: 'Turntable.FM')
Product.create(title: 'Netgear NeoTV Max')
Product.create(title: 'Scrivener for Windows')
Product.create(title: 'ADT Pulse Premier')
Product.create(title: 'Intuit QuickBooks Pro')
Product.create(title: 'Epson WorkForce WP-4540')
Product.create(title: 'Lytro Light-Field Camera')
Product.create(title: 'Microsoft Type Cover')
Product.create(title: 'Western Digital My Passport 2TB')
Product.create(title: 'Pinterest')
Product.create(title: 'Maingear Shift Super Stock')
Product.create(title: 'Panasonic HC-V700M')
Product.create(title: 'Sony XQD S Series')
Product.create(title: 'XCOM: Enemy Unknown')
Product.create(title: 'V-Moda VAMP')
Product.create(title: 'Synology DiskStation 712+')
Product.create(title: 'Microsoft Sculpt Touch Mouse')
Product.create(title: 'Lowes Iris')
Product.create(title: 'Logitech HD Pro Webcam C920')
Product.create(title: 'Asus Xonar Essence One')
Product.create(title: 'HP Officejet 150 Mobile All-in-One Printer')
Product.create(title: 'Razer Naga Expert MMO Gaming Mouse')
Product.create(title: 'Hero Academy')
Product.create(title: 'Sony Handycam HDR-PJ760V')
Product.create(title: 'Damn Small Linux')
Product.create(title: 'Axis P1344')
Product.create(title: 'Stardock Multiplicity 2.0')
Product.create(title: 'Apple TV')
Product.create(title: 'Dishonored')
Product.create(title: 'Lexar 128GB Professional 1000x CompactFlash')
Product.create(title: 'Sanebox')
Product.create(title: 'Rikomagic MK802')
Product.create(title: 'Telenav Scout')
Product.create(title: 'Apple Earpods')
Product.create(title: 'Cinemagram')
Product.create(title: 'Seagate Momentus XT Hybrid')
Product.create(title: 'Sony Cyber-shot RX100')
Product.create(title: 'Brother MFC-J4510DW')
Product.create(title: 'Ceton InfiniTV 4 USB')
Product.create(title: 'V-moda Crossfade M-80 (r2)')
Product.create(title: 'Sony PS3 Pulse Wireless Headset')
Product.create(title: 'Pinball Arcade')